config/routes.rb
Rails.application.routes.draw do
  resources :eeg_files do
  	collection do
  		get :search
  	end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "eeg_files#index"
end

app/models/eeg_file.rb
# == Schema Information
#
# Table name: eeg_files
#
#  id            :bigint(8)        not null, primary key
#  path          :string(255)
#  file_type     :string(255)
#  host          :string(255)
#  name          :string(255)
#  date          :string(255)
#  mrn           :string(255)
#  de_identified :boolean
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#  edf_plus      :boolean
#  edf           :boolean
#

class EegFile < ApplicationRecord
	validates_presence_of :path
	validates_uniqueness_of :path

	def self.search_around(name_tokens, from_date, to_date)
		@eeg_files = EegFile.by_name(name_tokens).by_date(from_date, to_date)
    @eeg_files
	end

	def self.by_name(tokens)
		# name format in nihon kohden is lastname, firstname
		# remove possible punctuations 
		tokens = tokens.collect{|t| t.gsub(',', '')}
		tokens = tokens.collect{|t| t.gsub('.', '')}
		# exepected two tokens, at least 1, otherwise it will not reach here
		# 
		if tokens.size > 2
			tokens = [tokens[0], tokens[-1]]
			files = EegFile.where('name in (?)', [tokens.join(", "), tokens.reverse.join(", ")])	
		elsif tokens.size == 2
			files = EegFile.where('name in (?)', [tokens.join(", "), tokens.reverse.join(", ")])	
		elsif tokens.size == 1
			files = EegFile.where('name like ?', "%#{tokens[0]}%")	
		else
			return EegFile.where('id is null')
		end
		files
	end

	def self.by_date(from_date, to_date)
		files = EegFile.where('date >= ? and date <= ?', from_date, to_date)
		files
	end 

	def print
		puts 'hello, world!'
	end

	def with_name?(name_tokens)
		tokens = tokens.collect{|t| t.gsub(',', '')}
		tokens = tokens.collect{|t| t.gsub('.', '')}
		if self.name.blank?
			return false
		else
			name = self.name.downcase
			if tokens.size > 2
				tokens = [tokens[0], tokens[-1]]	
			elsif tokens.size == 2
				tokens = tokens	
			elsif tokens.size == 1
				return name.include?(tokens.first.downcase)	
			else
				return false
			end
			result =  [tokens.join(", "), tokens.reverse.join(", ")].include?(name)
			return result
		end
	end

	def de_identify
		phi_file_types = ["BFT", "CMT", "CN2", "EEG", "LOG", "PNT", 'EGF']
		name_tokens = []
		# file_path = self.path.gsub('NKT', 'NKT3/NKT')
		file_path = self.path
		unless File.exists?(file_path)
			return
		end

		unless phi_file_types.include?(self.path[-3..-1])
			return
		end

		opic_id = nil
		local_patient_number = nil
		first_name = nil
		last_name = nil
		dob = nil
		entry = self.path.split('/').last
		patient = nil
		if self.name.present? or self.mrn.present?
			patient = Patient.find_by_name(self.name, self.date)
			
			if patient.blank?
				patient = Patient.find_by_mrn(self.mrn, self.date)
			end
		else
			data_name = self.path.split('/').last[0..-5]
			same_patient_files = EegFile.where('path like ?', "%#{data_name}.%")
		end

		if patient.present?
			opic_id = "#{patient.opic_id}"
			local_patient_number = patient.local_patient_number
			first_name = patient.first_name
			last_name = patient.last_name
			name_tokens = [first_name, last_name]
			
			if patient.dob.present?
				dob = patient.dob.strftime("%Y%m%d")
			end

			unless File.directory?(path)
				if entry.end_with?('PTN')
					replace_ptn_name(file_path, name_tokens, opic_id)
				elsif phi_file_types.include? entry[-3..-1]
					replace_name(file_path, name_tokens, opic_id)
					replace_mrn(file_path, mrn, local_patient_number)
				elsif entry[-3..-1] == 'EGF'
					de_egf(file_path, local_patient_number, opic_id)
				elsif entry[-3..-1] == 'LOG'
					de_txt(file_path, first_name, last_name, local_patient_number, dob);
				end
				self.de_identified = true
				self.patient_id = patient.id
				self.save
			end	
		end
	end

	def de_identify_tju
		phi_file_types = ["BFT", "CMT", "CN2", "EEG", "LOG", "PNT", 'EGF','pnt']
		name_tokens = []
		# file_path = self.path.gsub('NKT', 'NKT3/NKT')
		file_path = self.path
		unless File.exists?(file_path)
			return
		end

		unless phi_file_types.include?(self.path[-3..-1])
			return
		end

		opic_id = self.opic_id
		patient = Patient.where(opic_id: opic_id).first
		entry = self.path.split('/').last
		if patient.present?
			local_patient_number = patient.local_patient_number
			local_patient_number||=''
			first_name = patient.first_name
			last_name = patient.last_name
			name_tokens = [first_name, last_name]
			
			if patient.dob.present?
				dob = patient.dob.strftime("%Y%m%d")
			end

			unless File.directory?(path)
				if entry.end_with?('PTN')
					replace_ptn_name(file_path, name_tokens, opic_id)
				elsif phi_file_types.include? entry[-3..-1]
					replace_name(file_path, name_tokens, opic_id)
					replace_mrn(file_path, mrn, local_patient_number)
				elsif entry[-3..-1] == 'EGF'
					de_egf(file_path, local_patient_number, opic_id)
				elsif entry[-3..-1] == 'LOG'
					de_txt(file_path, first_name, last_name, local_patient_number, dob);
				end
				self.de_identified = true
				self.patient_id = patient.id
				self.save
			end	
		end
	end

	def de_identify_uiowa
		phi_file_types = ["BFT", "CMT", "CN2", "EEG", "LOG", "PNT", 'EGF','pnt']
		name_tokens = []
		# file_path = self.path.gsub('NKT', 'NKT3/NKT')
		file_path = self.path
		unless File.exists?(file_path)
			return
		end

		unless phi_file_types.include?(self.path[-3..-1])
			return
		end

		opic_id = self.opic_id
		patient = Patient.where(opic_id: opic_id).first
		entry = self.path.split('/').last
		if patient.present?
			local_patient_number = patient.local_patient_number
			local_patient_number||=''
			first_name = patient.first_name
			last_name = patient.last_name
			name_tokens = [first_name, last_name]
			
			if patient.dob.present?
				dob = patient.dob.strftime("%Y%m%d")
			end

			unless File.directory?(path)
				if entry.end_with?('PTN')
					replace_ptn_name(file_path, name_tokens, opic_id)
				elsif phi_file_types.include? entry[-3..-1]
					replace_name(file_path, name_tokens, opic_id)
					replace_mrn(file_path, mrn, local_patient_number)
				elsif entry[-3..-1] == 'EGF'
					de_egf(file_path, local_patient_number, opic_id)
				elsif entry[-3..-1] == 'LOG'
					de_txt(file_path, first_name, last_name, local_patient_number, dob);
				end
				self.de_identified = true
				self.patient_id = patient.id
				self.save
			end	
		end
	end

	def de_identify_nw
		phi_file_types = ["BFT", "CMT", "CN2", "EEG", "LOG", "PNT", 'EGF','pnt']
		name_tokens = []
		# file_path = self.path.gsub('NKT', 'NKT3/NKT')
		file_path = self.path
		unless File.exists?(file_path)
			return
		end

		unless phi_file_types.include?(self.path[-3..-1])
			return
		end

		opic_id = self.opic_id
		patient = Patient.where(opic_id: opic_id).first
		entry = self.path.split('/').last
		if patient.present?
			local_patient_number = patient.local_patient_number
			local_patient_number||=''
			first_name = patient.first_name
			last_name = patient.last_name
			name_tokens = [first_name, last_name]
			
			if patient.dob.present?
				dob = patient.dob.strftime("%Y%m%d")
			end

			unless File.directory?(path)
				if entry.end_with?('PTN')
					replace_ptn_name(file_path, name_tokens, opic_id)
				elsif phi_file_types.include? entry[-3..-1]
					replace_name(file_path, name_tokens, opic_id)
					replace_mrn(file_path, mrn, local_patient_number)
				elsif entry[-3..-1] == 'EGF'
					de_egf(file_path, local_patient_number, opic_id)
				elsif entry[-3..-1] == 'LOG'
					de_txt(file_path, first_name, last_name, local_patient_number, dob);
				end
				self.de_identified = true
				self.patient_id = patient.id
				self.save
			end	
		end
	end

	def de_identify_nw_prism
		phi_file_types = ["BFT", "CMT", "CN2", "EEG", "LOG", "PNT", 'EGF','pnt']
		name_tokens = []
		# file_path = self.path.gsub('NKT', 'NKT3/NKT')
		file_path = self.path
		unless File.exists?(file_path)
			return
		end

		unless phi_file_types.include?(self.path[-3..-1])
			return
		end

		opic_id = self.opic_id
		patient = Patient.where(opic_id: opic_id).first
		entry = self.path.split('/').last
		if patient.present?
			local_patient_number = patient.local_patient_number
			local_patient_number||=''
			first_name = patient.first_name
			last_name = patient.last_name
			name_tokens = [first_name, last_name]
			
			if patient.dob.present?
				dob = patient.dob.strftime("%Y%m%d")
			end

			unless File.directory?(path)
				if entry.end_with?('PTN')
					replace_ptn_name(file_path, name_tokens, opic_id)
				elsif phi_file_types.include? entry[-3..-1]
					replace_name(file_path, name_tokens, opic_id)
					replace_mrn(file_path, mrn, local_patient_number)
				elsif entry[-3..-1] == 'EGF'
					de_egf(file_path, local_patient_number, opic_id)
				elsif entry[-3..-1] == 'LOG'
					de_txt(file_path, first_name, last_name, local_patient_number, dob);
				end
				self.de_identified = true
				self.patient_id = patient.id
				self.save
			end	
		end
	end

	def de_egf(file_path, local_patient_number, opic_id)
		f = File.open(file_path, 'rb')
		content = f.read
		content = content.gsub(/ID=(\w)+\n/, "ID=#{local_patient_number}\n")
		content = content.gsub(/PATNAME=[\w,\s\/]+\n/, "PATNAME=#{opic_id}\n")
		content = content.gsub(/BIRTHD=[\w,\s\/]+\n/, "BIRTHD=\n")
		File.open(file_path, "wb") {|file| file.puts content }
	end

	def replace_name(file_path, name_tokens, opic_id)

		file_format = file_path[-3..-1]	
		name_offset=79
		name_size=20
		content = opic_id.ljust(name_size, ' ')
		IO.binwrite(file_path, content, name_offset)
		name_pnt_offset = 1582
		dob_pnt_offset = 1632
		dob_pnt_size = 10
		dob_de_content='01/01/0001'
		if file_format.upcase == 'PNT'
			IO.binwrite(file_path, content, name_pnt_offset)
			IO.binwrite(file_path, dob_de_content, dob_pnt_offset)
			replace_protocol_comment(file_path, name_tokens, opic_id)
		end
	end

	def replace_protocol_comment(file_path, name_tokens, opic_id)
		content = IO.binread(file_path)
		first_comment_offset = content.index('ProtocolComment')
		first_name_offset = content.index('ProtocolName')
		if first_name_offset.present?

app/controllers/eeg_files_controller.rb
class EegFilesController < ApplicationController
  before_action :set_eeg_file, only: [:show, :edit, :update, :destroy]

  # GET /eeg_files
  # GET /eeg_files.json
  def index
    @eeg_files = EegFile.limit(200)
  end

  # GET /eeg_files/search
  # render index.html.erb

  def search
    if params[:name].blank?
      flash[:warning] = "Name cannot be blank for search"
      redirect_to root_path
      return
    end

    if params[:from_date].blank? or params[:to_date].blank?
      flash[:warning] = "Date cannot be blank for search"
      redirect_to root_path
      return
    end

    name_tokens = params[:name].strip.split
    begin
      from_date = Date.parse(params[:from_date]).strftime("%Y%m%d")
      to_date = Date.parse(params[:to_date]).strftime("%Y%m%d")
    rescue
      flash[:warning] = "Date format invalid: please use yyyy/mm/dd"
      redirect_to root_path      
      return
    end
    @name = params[:name]
    @from_date = params[:from_date]
    @to_date = params[:to_date]

    @eeg_files = EegFile.search_around(name_tokens, from_date, to_date)
    
    render 'index'
  end

  # GET /eeg_files/1
  # GET /eeg_files/1.json
  def show
  end

  # GET /eeg_files/new
  def new
    @eeg_file = EegFile.new
  end

  # GET /eeg_files/1/edit
  def edit
  end

  # POST /eeg_files
  # POST /eeg_files.json
  def create
    @eeg_file = EegFile.new(eeg_file_params)

    respond_to do |format|
      if @eeg_file.save
        format.html { redirect_to @eeg_file, notice: 'Eeg file was successfully created.' }
        format.json { render :show, status: :created, location: @eeg_file }
      else
        format.html { render :new }
        format.json { render json: @eeg_file.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /eeg_files/1
  # PATCH/PUT /eeg_files/1.json
  def update
    respond_to do |format|
      if @eeg_file.update(eeg_file_params)
        format.html { redirect_to @eeg_file, notice: 'Eeg file was successfully updated.' }
        format.json { render :show, status: :ok, location: @eeg_file }
      else
        format.html { render :edit }
        format.json { render json: @eeg_file.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /eeg_files/1
  # DELETE /eeg_files/1.json
  def destroy
    @eeg_file.destroy
    respond_to do |format|
      format.html { redirect_to eeg_files_url, notice: 'Eeg file was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_eeg_file
      @eeg_file = EegFile.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def eeg_file_params
      params.require(:eeg_file).permit(:path, :file_type, :host, :name, :date, :mrn, :de_identified)
    end
end

app/helpers/eeg_files_helper.rb
module EegFilesHelper
end

app/views/eeg_files/_form.html.erb
<%= form_with(model: eeg_file, local: true) do |form| %>
  <% if eeg_file.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(eeg_file.errors.count, "error") %> prohibited this eeg_file from being saved:</h2>

      <ul>
      <% eeg_file.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :path %>
    <%= form.text_field :path %>
  </div>

  <div class="field">
    <%= form.label :type %>
    <%= form.text_field :type %>
  </div>

  <div class="field">
    <%= form.label :host %>
    <%= form.text_field :host %>
  </div>

  <div class="field">
    <%= form.label :first_name %>
    <%= form.text_field :first_name %>
  </div>

  <div class="field">
    <%= form.label :last_name %>
    <%= form.text_field :last_name %>
  </div>

  <div class="field">
    <%= form.label :middle_name %>
    <%= form.text_field :middle_name %>
  </div>

  <div class="field">
    <%= form.label :date %>
    <%= form.text_field :date %>
  </div>

  <div class="field">
    <%= form.label :mrn %>
    <%= form.text_field :mrn %>
  </div>

  <div class="field">
    <%= form.label :de_identified %>
    <%= form.check_box :de_identified %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/eeg_files/edit.html.erb
<h1>Editing Eeg File</h1>

<%= render 'form', eeg_file: @eeg_file %>

<%= link_to 'Show', @eeg_file %> |
<%= link_to 'Back', eeg_files_path %>

app/views/eeg_files/index.html.erb
<p id="notice"><%= notice %></p>

<div style='float: left'>
  <%= form_tag search_eeg_files_path, method: 'get' do %>
    <h1>EEG Files</h1> 
    Name <%= text_field_tag 'name', @name||'' %>
    Date From<%= text_field_tag 'from_date', @from_date||'', autocomplete: 'off' %>
    Date To<%= text_field_tag 'to_date', @to_date||'', autocomplete: 'off' %>
    <%= submit_tag 'Search'%>
  <% end %>
</div>
<div style='clear:both'></div>
<br>

<hr>
<% if @eeg_files.present? %>
<table id='file_table'>
  <thead>
    <tr>
      <th>Path</th>
      <th>Type</th>
      <th>Name</th>
      <th>Date</th>
      <th>Mrn</th>
    </tr>
  </thead>

  <tbody>
    <% @eeg_files.each do |eeg_file| %>
      <tr>
        <td><%= eeg_file.path %></td>
        <td><%= eeg_file.file_type %></td>       
        <td><%= eeg_file.name %></td>
        <td><%= eeg_file.date %></td>
        <td><%= eeg_file.mrn %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<% end %>

<br>

<script>
  // $('#file_table').dataTable({
  //    "pageLength": 100
  // });
  $('#name').focus();
  $('#from_date, #to_date').datepicker({
    changeYear: true,
    changeMonth: true,
    dateFormat: 'yy-mm-dd',
    yearRange: '-122:+10'
  });
</script>

app/views/eeg_files/new.html.erb
<h1>New Eeg File</h1>

<%= render 'form', eeg_file: @eeg_file %>

<%= link_to 'Back', eeg_files_path %>

app/views/eeg_files/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Path:</strong>
  <%= @eeg_file.path %>
</p>

<p>
  <strong>Type:</strong>
  <%= @eeg_file.type %>
</p>

<p>
  <strong>Host:</strong>
  <%= @eeg_file.host %>
</p>

<p>
  <strong>First name:</strong>
  <%= @eeg_file.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @eeg_file.last_name %>
</p>

<p>
  <strong>Middle name:</strong>
  <%= @eeg_file.middle_name %>
</p>

<p>
  <strong>Date:</strong>
  <%= @eeg_file.date %>
</p>

<p>
  <strong>Mrn:</strong>
  <%= @eeg_file.mrn %>
</p>

<p>
  <strong>De identified:</strong>
  <%= @eeg_file.de_identified %>
</p>

<%= link_to 'Edit', edit_eeg_file_path(@eeg_file) %> |
<%= link_to 'Back', eeg_files_path %>